# Generated by Django 4.2.4 on 2023-09-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_post_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
