# Generated by Django 4.2.4 on 2023-09-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_blogs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='Status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
