# Generated by Django 4.2.4 on 2023-09-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_blogs_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='author',
        ),
    ]
